# Generated by Django 5.2.14 on 2026-05-13 01:21

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.CharField(default=core.models.make_object_id, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('delta', models.IntegerField()),
                ('reason', models.CharField(choices=[('receiving', 'Penerimaan'), ('sale', 'Penjualan'), ('adjustment', 'Penyesuaian'), ('void', 'Void')], max_length=16)),
                ('ref_type', models.CharField(blank=True, default='', max_length=32)),
                ('ref_id', models.CharField(blank=True, default='', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='store.store')),
            ],
            options={
                'ordering': ['-created_on'],
                'indexes': [models.Index(fields=['store', 'product', '-created_on'], name='stock_stock_store_i_f92154_idx'), models.Index(fields=['store', '-created_on'], name='stock_stock_store_i_2f8404_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoreStock',
            fields=[
                ('id', models.CharField(default=core.models.make_object_id, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('qty', models.IntegerField(default=0)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='store.store')),
            ],
            options={
                'indexes': [models.Index(fields=['store'], name='stock_store_store_i_cae8c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='uniq_storestock_store_product')],
            },
        ),
    ]
