# Generated by Django 5.2.14 on 2026-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="delta",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="storestock",
            name="qty",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
