# Generated by Django 5.2.14 on 2026-05-13 00:06

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cashier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierSession',
            fields=[
                ('id', models.CharField(default=core.models.make_object_id, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(db_index=True, max_length=40, unique=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.cashier')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashier_sessions', to='core.store')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
