# Generated by Django 5.2.14 on 2026-05-14 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
        ("tenant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="uniq_product_barcode_per_tenant",
        ),
        migrations.AddField(
            model_name="product",
            name="archived_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("barcode__isnull", False), ("archived_at__isnull", True)),
                fields=("tenant", "barcode"),
                name="uniq_product_barcode_per_tenant",
            ),
        ),
    ]
