# Generated by Django 5.2.14 on 2026-05-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_remove_product_uniq_product_barcode_per_tenant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="bundle_label",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="bundle_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="bundle_qty",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
