# Generated by Django 5.2.14 on 2026-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_bundle_label_product_bundle_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_weighted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_label",
            field=models.CharField(default="pcs", max_length=8),
        ),
    ]
