# Generated by Django 5.2.14 on 2026-05-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BarcodeCatalog",
            fields=[
                ("barcode", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "barcode_catalog",
            },
        ),
    ]
