# Generated by Django 5.2.14 on 2026-05-13 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cashier", "0001_initial"),
        ("product", "0001_initial"),
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("subtotal", models.IntegerField()),
                ("tendered", models.IntegerField()),
                ("change", models.IntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cashier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="cashier.cashier",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="store.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on"],
            },
        ),
        migrations.CreateModel(
            name="SaleLine",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.models.make_object_id,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("qty", models.PositiveIntegerField()),
                ("unit_price", models.IntegerField()),
                ("line_total", models.IntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="product.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sale.sale",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["store", "-created_on"], name="sale_sale_store_i_b45902_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["cashier", "-created_on"], name="sale_sale_cashier_c4e0ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleline",
            index=models.Index(fields=["sale"], name="sale_saleli_sale_id_57f7e9_idx"),
        ),
        migrations.AddIndex(
            model_name="saleline",
            index=models.Index(
                fields=["product", "-created_on"], name="sale_saleli_product_6fb8fe_idx"
            ),
        ),
    ]
