# Generated by Django 5.2.14 on 2026-05-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleline",
            name="bundle_qty",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="saleline",
            name="is_bundle",
            field=models.BooleanField(default=False),
        ),
    ]
