# Generated by Django 5.2.14 on 2026-05-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sale", "0002_saleline_bundle_qty_saleline_is_bundle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saleline",
            name="qty",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
